arch: transformer_multibranch_v2_iwslt_de_en
no-progress-bar: true 

optimizer: adam
lr: 0.0005
source-lang: de
target-lang: en
label-smoothing: 0.1
dropout: 0.2
max-tokens: 4096
clip-norm: 0.0
min-lr: 1e-09
lr-scheduler: inverse_sqrt
weight-decay: 0.0001
criterion: label_smoothed_cross_entropy
max-update: 50000
warmup-updates: 4000
warmup-init-lr: 1e-07
adam-betas: (0.9, 0.98)
fp16: False

weight-dropout: 0.1
encoder-glu: 0
decoder-glu: 0
encoder-branch-type: [attn:1:160:4, lightweight:default:160:4]
decoder-branch-type: [attn:1:160:4, lightweight:default:160:4]
conv-linear: true

encoder-embed-dim: 320
decoder-embed-dim: 320
encoder-ffn-embed-dim: 320
decoder-ffn-embed-dim: 320
